### ISSUE TITLE
command prompt error.

### ISSUE THREAD

**Issue by jignesh87** [Flynsarmy/PHPWebSocket-Chat#10]
Hi thanks for your code.
but, when i type  "php5 ./server.php" command it giving following error.

C:\xampp\htdocs\PHPWebSocket-Chat-master>php5 ./server.php

'php5' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Flynsarmy** [comment]
Use php instead of php5. If that doesn't work either you need to add php to your PATH. Google will let you know how that's done.

**Comment by jignesh87** [comment]
Thank you its connect.
I am sending messages but it still not displaying..
