### ISSUE TITLE
Socket_create() Missing PHP 5

### ISSUE THREAD

**Issue by adminy** [Flynsarmy/PHPWebSocket-Chat#17]
PHP Fatal error:  Call to undefined function socket_create() in ../public_html/chat/class.PHPWebSocket.php on line 103

PHP 5.4.20 (cli)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies

**Comment by w-jerome** [comment]
You have found the problem ? :)
What is it ?

**Comment by adminy** [comment]
@w-jerome Sorry for the late reply. The problem was that the php I was using was not compiled with sockets as a flag/option so it was missing it.
