### ISSUE TITLE
 I am doing something wrong?

### ISSUE THREAD

**Issue by stagfoo** [Flynsarmy/PHPWebSocket-Chat#5]
This might seem like a dumb error because im new to sockets and ssh. I have run the server over at <code>http://stagfoo.com/echo-chat/</code> but i get the message <code>disconnected</code> whenever i go to the client page and then no messages are seen on other clients. I am doing something wrong?

**Comment by adminy** [comment]
Yes as @shellus mentioned Its highly possible that hosting has no socket support. But if they do What are you doing ? I mean your url IMPLIES you are using port 80, and you are probably trying the same port for the sockets yeah? That won't work.
